- type: department
  id: Frontier
  name: department-Frontier
  description: department-NF-description
  color: "#334E6D"
  weight: 50 # accounted for in jobs
  roles:
  - StationRepresentative
  - DirectorOfCare
  - StationTrafficController
  - Valet # nyano
  - NFJanitor
  - MailCarrier # nyano
  - SecurityGuard
  - MedicalNurse # Frontier
  - Therapist # Frontier

- type: department
  id: Antag
  name: department-Antag
  description: department-NFAntag-description
  color: "#DE3A3A"
  weight: -20 # accounted for in jobs
  roles:
  - NFPirateCaptain
  - NFPirateFirstMate
  - NFPirate
  - Smuggler #Coyote
  - Escort #Coyote
  - Prisoner #nyano
  - RipperDoc #Coyote
