# The job itself
# Chaplain - ERP RPI boost, aura, free uh, bocadillo?
- type: job
  id: Chaplain
  name: job-name-chaplain
  description: job-description-chaplain
  playTimeTracker: JobChaplain
  icon: "JobIconChaplain"
  supervisors: job-supervisors-chaplain
  weight: 40 # Prioritize station & department jobs
  displayWeight: 3 # idk
  access:
  - Service
  - Janitor
  - Maintenance
  - External
  - Frontier
  accessGroups:
  - GeneralAccess
  special:
  - !type:AddImplantSpecial
    implants: [ TrackingImplant ]
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift
  - !type:AddRpiAuraSpecial
    aurasToAdd:
    - rpiAuraChaplain
  - !type:RpiChatJudgementModifierSpecial
    modsToAdd:
    - rpiChatJudgementModifierMassageChaplain
  - !type:AddComponentSpecial
    components:
    - type: BibleUser #Lets them heal with bibles

# play time tracker
#- type: playTimeTracker
#  id: JobChaplain

#- type: entity
#  id: SpawnPointChaplain
#  parent: SpawnPointPassenger
#  name: chaplain spawn point
#  components:
#  - type: SpawnPoint
#    job_id: Chaplain

- type: startingGear
  id: ChaplainGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: ChaplainPDA
    ears: ClothingHeadsetService
  storage:
    back:
    - Bible
    - RubberStampChaplain
    - EncryptionKeyService
    - ShipVoucherCoyoteChaplain

# Food Service Role Loadout
- type: roleLoadout
  id: JobChaplain
  groups:
  - ContractorHead
  - ContractorNeck
  - PilotJumpsuit
  - ContractorGloves
  - ContractorBackpack
  - ContractorOuterClothing
  - ContractorForcedOuterClothing
  - ContractorShoes
  - ContractorFace
  - ContractorGlasses
  - ContractorBelt
  - ContractorEars
  - ContractorEncryptionKey
  - ContractorBoxSurvival
  - ContractorPDA
  - ContractorWallet
  - ContractorCartridge
  - ContractorImplanter
  - ContractorBackpackItems
  - ContractorHandItems
  - NFSpeciesSpecific
