- type: job
  id: Chaplain
  name: job-name-chaplain
  description: job-description-chaplain
  playTimeTracker: JobChaplain
  #requirements:
  #  - !type:OverallPlaytimeRequirement
  #    time: 10800
  startingGear: CSChaplainGear
  alwaysUseSpawner: false
  icon: "JobIconChaplain"
  supervisors: job-supervisors-hire
  weight: 40
  displayWeight: 3
  canBeAntag: false
  accessGroups:
  - GeneralAccess
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift
  - !type:AddRpiAuraSpecial
    aurasToAdd:
    - rpiAuraChaplain
  - !type:RpiChatJudgementModifierSpecial
    modsToAdd:
    - rpiChatJudgementModifierMassageChaplain
  - !type:AddComponentSpecial
    components:
    - type: BibleUser

- type: startingGear
  id: CSChaplainGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: ChaplainPDA
    ears: ClothingHeadsetService
  storage:
    back:
    - Bible
    - RubberStampChaplain
    - EncryptionKeyService
    - ShipVoucherCoyoteChaplain

- type: roleLoadout
  id: JobChaplain
  groups:
  - ContractorHead
  - ContractorNeck
  - CSChaplainJumpsuit
  - ContractorGloves
  - ContractorBackpack
  - ContractorOuterClothing
  - ContractorForcedOuterClothing
  - ContractorShoes
  - ContractorFace
  - ContractorGlasses
  - ContractorBelt
  - ContractorEars
  - ContractorEncryptionKey
  - ContractorBoxSurvival
  - ContractorPDA
  - ContractorWallet
  - ContractorCartridge
  - ContractorImplanter
  - ContractorBackpackItems
  - ContractorHandItems
  - NFSpeciesSpecific
