# The job itself
# massage therapist + ERPer + touchytouchy
- type: job
  id: MassageTherapist
  name: job-name-massage-therapist
  description: job-description-massage-therapist
  playTimeTracker: JobMassageTherapist
  icon: "JobIconBoxer"
  supervisors: job-supervisors-massage-therapist
  startingGear: MassageTherapistGear
  weight: 40 # Prioritize station & department jobs
  displayWeight: 3 # idk
  access:
  - Service
  - Janitor
  - Maintenance
  - External
  - Frontier
  accessGroups:
  - GeneralAccess
  special:
  - !type:AddImplantSpecial
    implants: [ TrackingImplant ]
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift
  - !type:AddRpiAuraSpecial
    aurasToAdd:
    - rpiAuraMassageTherapist
  - !type:RpiChatJudgementModifierSpecial
    modsToAdd:
    - rpiChatJudgementModifierMassageTherapist

# play time tracker
- type: playTimeTracker
  id: JobMassageTherapist

- type: entity
  id: SpawnPointMassageTherapist
  parent: SpawnPointPassenger
  name: massage therapist spawn point
  components:
  - type: SpawnPoint
    job_id: MassageTherapist

# starting gear
- type: startingGear
  id: MassageTherapistGear
  storage:
    back:
    - EncryptionKeyService
    - ShipVoucherCoyoteMassageTherapist

# Food Service Role Loadout
- type: roleLoadout
  id: JobMassageTherapist
  groups:
  - ContractorHead
  - ContractorNeck
  - PilotJumpsuit
  - ContractorGloves
  - ContractorBackpack
  - ContractorOuterClothing
  - ContractorForcedOuterClothing
  - ContractorShoes
  - ContractorFace
  - ContractorGlasses
  - ContractorBelt
  - ContractorEars
  - ContractorEncryptionKey
  - ContractorBoxSurvival
  - ContractorPDA
  - ContractorWallet
  - ContractorCartridge
  - ContractorImplanter
  - ContractorBackpackItems
  - ContractorHandItems
  - NFSpeciesSpecific

- type: chameleonOutfit
  id: MassageTherapistChameleonOutfit
  job: MassageTherapist
  equipment:
    head: ClothingHeadHatChef
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskItalianMoustache
    neck: ClothingNeckScarfStripedBrown
    outerClothing: ClothingOuterJacketChef
    gloves: ClothingHandsGlovesColorWhite
    shoes: ClothingShoesChef

