- type: job
  id: PublicAffairsLiaison
  name: job-name-pal
  description: job-description-public-affairs-liaison
  playTimeTracker: JobPublicAffairsLiaison
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 129600 # 36 hours
    - !type:DepartmentTimeRequirement
      department: Security
      time: 21600 # 6 hours
  alternateRequirementSets:
    longerPlaytimeLessSec:
    - !type:OverallPlaytimeRequirement
      time: 360000 # 100 hours
    - !type:DepartmentTimeRequirement # CS - require at least some security time so the whitelist intent functions
      department: Security
      time: 3600 # 1 hour
  startingGear: PublicAffairGear
  icon: "JobIconPublicAffairsLiaison"
  supervisors: job-supervisors-cadet
  canBeAntag: false
  weight: 105
  displayWeight: 16
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: PublicAffairGear
  equipment:
    pocket1: NFHyperlinkBookSpaceLaw
    pocket2: BoxFolderClipboardPal
  storage:
    back:
    - Flash
    - BoxFolderPalBrown
    - BoxFolderNfsdForms
    - RubberStampPal

- type: chameleonOutfit
  id: PublicAffairsLiaisonChameleonOutfit
  job: PublicAffairsLiaison
  hasMindShield: true
  equipment:
    head: ClothingHeadHatBowlerHat
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskBreath
    neck: ClothingNeckLawyerbadge
    outerClothing: ClothingOuterWinterColorBlack
    gloves: ClothingHandsGlovesColorBlack
